# Generated by Django 5.1.1 on 2024-09-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=79)),
                ('text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.architecturegroup', verbose_name='arc_objects')),
            ],
        ),
    ]
