# Generated by Django 5.1.1 on 2024-09-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0002_architectureobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectureobject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc_objects', to='architecture.architecturegroup'),
        ),
    ]
