# Generated by Django 5.1.1 on 2024-09-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0003_alter_architectureobject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
